name: Node.js CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nuxt/actions-yarn@master
      with:
        args: install
        
    - uses: nuxt/actions-yarn@master
      with:
        args: global add firebase-tools

    - name: functions install
      run: |
        cd ./functions
        npm install

    - uses: nuxt/actions-yarn@master
      with:
        args: generate

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
