name: Node.js CI
on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build
      run: |
        cd ./functions
        npm install

  deploy:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    name: Deploy
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build each site
        run: |
          cd ./functions
          npm install

      - name: Ready to deploy
        run: |
          yarn global add firebase-tools
          yarn
          yarn generate
          cd functions
          npm install
      - name: Deploy to Firebase
        run: |
          firebase deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
