name: Node.js CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nuxt/actions-yarn@master
      with:
        args: install

    - name: functions install install firebase-tools
      run: |
        yarn global add firebase-tools
        cd ./functions
        npm install

    - uses: nuxt/actions-yarn@master
      with:
        args: generate

    - name: deploy
      run: firebase deploy --token $FIREBASE_TOKEN
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
