name: Node.js CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: yarn install
      uses: nuxt/actions-yarn@master
      with:
        args: install
        
    - name: install firebase-tools
      uses: nuxt/actions-yarn@master
      with:
        args: global add firebase-tools

    - name: functions install
      run: |
        cd ./functions
        npm install

    - name: nuxt generate
      uses: nuxt/actions-yarn@master
      with:
        args: generate
      env:
        process.env.FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        process.env.FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        process.env.FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        process.env.FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        process.env.FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        process.env.FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        process.env.FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        process.env.ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        process.env.ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        process.env.STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: "j4k1-b789f"
